<?php

namespace TRando\MainBundle\Repository;

/**
 * likesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class likesRepository extends \Doctrine\ORM\EntityRepository
{
}
