<?php

namespace TRando\MainBundle\Repository;

/**
 * participantListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participantListRepository extends \Doctrine\ORM\EntityRepository
{
}
