<?php

namespace TRando\MainBundle\Repository;

/**
 * subscribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class subscribeRepository extends \Doctrine\ORM\EntityRepository
{
}
