<?php

namespace TRando\MainBundle\Repository;

/**
 * TipsandTricksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipsandTricksRepository extends \Doctrine\ORM\EntityRepository
{
}
